version: '3'
services:
  app:
    build: .
    depends_on: 
      - sql
      - redis
    volumes:
      - $PWD/media:/app/media
    port:
      - 8080:80
  sql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    volumes:
      - $PWD/sql:/var/lib/mysql
  redis:
    image: redis
